### ISSUE TITLE
Error: Failed to launch chrome!

### ISSUE THREAD

**Issue by chgwan** [aqiongbei/buy_pig_plan#10]
TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/root/buy_pig_plan/node_modules/puppeteer/lib/Launcher.js:342:14)
    at Interface.helper.addEventListener (/root/buy_pig_plan/node_modules/puppeteer/lib/Launcher.js:331:50)
    at emitNone (events.js:111:20)
    at Interface.emit (events.js:208:7)
    at Interface.close (readline.js:370:8)
    at Socket.onend (readline.js:149:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
Error: Failed to launch chrome!
[0612/225018.863039:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
老哥这个问题怎么解决呀

**Comment by ritianaixuexi** [comment]
同问，也遇到这个问题。。尝试了安装chromium，用的是`curl https://intoli.com/install-google-chrome.sh | bash`这个给出的 安装后还是跟上面一样

**Comment by creativemango** [comment]
同问，我也遇到了这个问题
