### ISSUE TITLE
留言模式有问题不能运行

### ISSUE THREAD

**Issue by TianMo-ZhangSan** [aqiongbei/buy_pig_plan#12]
Error: Cannot parse config file: 'C:\Users\AI1\bomer\config\production.json': SyntaxError: Unexpected token } in JSON at position 464
    at Config.util.parseFile (C:\Users\AI1\bomer\node_modules\config\lib\config.js:963:11)
    at C:\Users\AI1\bomer\node_modules\config\lib\config.js:725:28
    at Array.forEach (<anonymous>)
    at C:\Users\AI1\bomer\node_modules\config\lib\config.js:721:14
    at Array.forEach (<anonymous>)
    at Config.util.loadFileConfigs (C:\Users\AI1\bomer\node_modules\config\lib\config.js:720:13)
    at new Config (C:\Users\AI1\bomer\node_modules\config\lib\config.js:136:27)
    at Object.<anonymous> (C:\Users\AI1\bomer\node_modules\config\lib\config.js:1797:31)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! buy_pig_plan@1.0.0 start: `cross-env NODE_ENV=production node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the buy_pig_plan@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AI1\AppData\Roaming\npm-cache\_logs\2019-07-26T07_01_05_065Z-debug.log

**Comment by TianMo-ZhangSan** [comment]
解决。是少了符号。
顺便sleeptime是不是可以调节。

**Comment by aqiongbei** [comment]
可以自己设置。留言模式其实是不需要`sleepTime`的，可以设置为0。在这个地方改。
```sh
 "attack": {
        "interval": 300000// sleepTime
    }
```
