### ISSUE TITLE
跑不起来

### ISSUE THREAD

**Issue by smkw33d** [aqiongbei/buy_pig_plan#5]
没接触过node 请问这种情况如何处理
`C:\Users\Liu\buy_pig_plan>npm start

> buy_pig_plan@1.0.0 start C:\Users\Liu\buy_pig_plan
> cross-env NODE_ENV=production node app.js

WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:427:7)
    at getFilename (C:\Users\Liu\buy_pig_plan\utils\util.js:28:35)
    at Object.getURLList (C:\Users\Liu\buy_pig_plan\utils\util.js:20:20)
    at Object.<anonymous> (C:\Users\Liu\buy_pig_plan\app.js:17:33)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! buy_pig_plan@1.0.0 start: `cross-env NODE_ENV=production node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the buy_pig_plan@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by aqiongbei** [comment]
用`npm run debug`跑起来的吗？

**Comment by aqiongbei** [comment]
`production`环境下有些bug，已经修复了推上去了，你更新一下代码再试试。看能不能解决问题

**Comment by smkw33d** [comment]
依旧有问题。
[2019-04-27T15_34_35_353Z-debug.log](https://github.com/aqiongbei/buy_pig_plan/files/3124038/2019-04-27T15_34_35_353Z-debug.log)
这是`production`环境下的log
[2019-04-27T15_36_04_616Z-debug.log](https://github.com/aqiongbei/buy_pig_plan/files/3124039/2019-04-27T15_36_04_616Z-debug.log)
这个是`debug`

**Comment by smkw33d** [comment]
问题已解决，感谢指导。我用的是comment模式，结果都是failed，是否影响实际效果？

**Comment by smkw33d** [comment]
都是这种`STATUS: failed MSG:[TIME OUT ERROR] TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded`

**Comment by aqiongbei** [comment]
会影响效果的。因为超时的话相当于任务失败。这是比较常见的情况，因为很多这种网站就不维护，网站打开速度奇慢，因为网站数量还行，所以多跑跑应该可以弥补的。

**Comment by nogoodwh** [comment]
你好，
       我在使用你的代码时出现了问题，想麻烦你能抽空帮我解决一下。
       当我在用production模式运行你的程序时，一直没反应，我不得不中止这个批处理：

D:\project\buy_pig_plan-master>npm start

> buy_pig_plan@1.0.0 start D:\project\buy_pig_plan-master
> cross-env NODE_ENV=production node app.js

WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
i got SIGINT
终止批处理操作吗(Y/N)? y

运行情况是以上这样的，我用debug模式运行就是正常的：

==================TASK TIMES: 1==================
TASK INFO: WEB NAME: 徐州市建筑工人医院 WEB TYPE: baidu_lxb
TASK RESULT: STATUS: failed MSG:[TIME OUT ERROR] TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
USED TIME: 30.013 S
SLEEP TIME: 0 S
==================TASK TIMES: 2==================
TASK INFO: WEB NAME: 浙江费玺尔流体设备有限公司 WEB TYPE: baidu_lxb
TASK RESULT: STATUS: failed MSG:[TIME OUT ERROR] TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
USED TIME: 30.004 S
SLEEP TIME: 0 S

只是网页一直都没响应而已（我估计这跟这些网页都不用了有关吧），我是nodejs 的萌新，请教一下大神，这个production模式下的问题应该怎么解决？
